postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "edklevel0"
  db_name: "postgres"
  ssl_mode: "disable"

nats:
  cluster_id: "test-cluster"
  client_id: "stan-sub"
  url: "nats://localhost:4222"
  subject: "orders"

server:
  network: "tcp"
  IP: "0.0.0.0"
  port: "3000"
  timeout: 5
  shutdown: 3
  static_storage: "static"